---
version: 2
jobs:
    node-latest: &test
        docker:
            - image: circleci/node:latest
        working_directory: ~/cli
        steps:
            - checkout
            - restore_cache: &restore_cache
                  keys:
                      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
                      - v1-npm-{{checksum ".circleci/config.yml"}}
            - run:
                  name: Install dependencies
                  command: npm install
            - run: ./bin/run --version
            - run: ./bin/run --help
    node-11:
        <<: *test
        docker:
            - image: circleci/node:11
    node-8:
        <<: *test
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - restore_cache: &restore_cache
                  keys:
                      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
                      - v1-npm-{{checksum ".circleci/config.yml"}}
            - run:
                  name: Install dependencies
                  command: npm install
            - run: ./bin/run --version
            - run: ./bin/run --help
    node-10:
        <<: *test
        docker:
            - image: circleci/node:10
    cache:
        <<: *test
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
                  paths:
                      - ~/cli/node_modules
                      - ~/.npm
                      - /usr/local/lib/node_modules

workflows:
    version: 2
    'hydrogen-cli':
        jobs:
            - node-8
            - node-10
            - node-11
            - cache:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
